-- =====================================================================
-- DEMO PORTAL — sample data, "Try demo" login and nightly reset
-- Run in Supabase > SQL Editor AFTER supabase_setup.sql, supabase_docs.sql,
-- supabase_hr.sql and supabase_extras.sql. Safe to run again.
--
-- What it does
--   1. stores the sample data (invented companies, people and numbers)
--   2. creates the logins: "demo" (used by the Try demo button) plus a few
--      sample users that only appear in lists (they cannot sign in)
--   3. demo_reset(): wipes everything and loads the sample data again,
--      with all dates moved so the demo always looks current
--   4. schedules demo_reset() every night at 03:00 Riyadh time and a
--      small login repair every hour (needs the Cron extension)
--   5. runs demo_reset() once now
--
-- This file is generated by tools/make_demo_seed.py — edit the data there.
-- =====================================================================

-- 1. sample data ------------------------------------------------------
create table if not exists public.demo_seed (
  id   int primary key default 1 check (id = 1),
  data jsonb not null,
  last_reset timestamptz,
  last_manual_reset timestamptz
);
alter table public.demo_seed enable row level security;          -- no policies: the website cannot read it
revoke all on public.demo_seed from anon, authenticated;
insert into public.demo_seed (id, data) values (1, $seed$__SEED_JSON__$seed$::jsonb)
on conflict (id) do update set data = excluded.data;

-- @D-12 -> the date 12 days ago, @D5 -> in 5 days, @Y -> this year
create or replace function public.demo_fill(t text, p_today date)
returns text language plpgsql immutable as $$
declare m text[];
begin
  t := replace(t, '@Y', to_char(p_today, 'YYYY'));
  loop
    m := regexp_match(t, '@D(-?\d+)');
    exit when m is null;
    t := regexp_replace(t, '@D' || m[1] || '(?![0-9])', to_char(p_today + m[1]::int, 'YYYY-MM-DD'), 'g');
  end loop;
  return t;
end $$;

-- 2. logins -----------------------------------------------------------
-- creates (or repairs) a Supabase Auth login and returns its id
create or replace function public.demo_login(p_email text, p_password text)
returns uuid language plpgsql security definer set search_path = public, extensions, auth as $$
declare v_id uuid;
begin
  select id into v_id from auth.users where lower(email) = lower(p_email);
  if v_id is null then
    v_id := gen_random_uuid();
    insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                            raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                            confirmation_token, recovery_token, email_change, email_change_token_new)
    values ('00000000-0000-0000-0000-000000000000', v_id, 'authenticated', 'authenticated', lower(p_email),
            extensions.crypt(p_password, extensions.gen_salt('bf')), now(),
            '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '');
    insert into auth.identities (id, user_id, provider_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
    values (gen_random_uuid(), v_id, v_id::text, jsonb_build_object('sub', v_id::text, 'email', lower(p_email), 'email_verified', true),
            'email', now(), now(), now());
  else
    -- put the password and e-mail back, in case a visitor changed them
    update auth.users set encrypted_password = extensions.crypt(p_password, extensions.gen_salt('bf')),
           email = lower(p_email), email_confirmed_at = coalesce(email_confirmed_at, now()), updated_at = now()
     where id = v_id;
  end if;
  return v_id;
end $$;
revoke all on function public.demo_login(text, text) from public, anon, authenticated;

-- hourly: keeps the demo login working even if someone changed its password
create or replace function public.demo_fix_login()
returns void language plpgsql security definer set search_path = public as $$
declare s jsonb := (select data->'settings' from public.demo_seed where id = 1); v_id uuid;
begin
  v_id := public.demo_login((s->>'demo_user') || '@' || (s->>'domain'), s->>'demo_password');
  update public.portal_users set active = true, is_admin = true, docs_role = 'manager', inv_role = 'admin', hr_role = 'admin'
   where id = v_id;
end $$;
revoke all on function public.demo_fix_login() from public, anon, authenticated;

-- 3. the reset --------------------------------------------------------
create or replace function public.demo_reset()
returns text language plpgsql security definer set search_path = public, extensions as $$
declare
  S       jsonb := (select data from public.demo_seed where id = 1);
  today   date  := (now() at time zone 'Asia/Riyadh')::date;
  dom     text  := S->'settings'->>'domain';
  r       jsonb;
  v_id    uuid;
  v_emp   uuid;
  v_doc   uuid;
  v_pay   uuid;
  v_inv   jsonb;
  v_user  jsonb := '{}';
  v_mgr   uuid;
  d       date;
  n_docs  int := 0;
  off_day int;
begin
  if S is null then raise exception 'demo_seed is empty: run supabase_demo.sql again'; end if;
  if to_regclass('public.docs_payments') is null or to_regclass('public.hr_salary_payments') is null or to_regclass('public.inv_counts') is null then
    raise exception 'Some portal tables are missing. Run supabase_install.sql (it contains everything), not supabase_demo.sql on its own.';
  end if;
  perform pg_advisory_xact_lock(hashtext('demo_reset'));
  S := public.demo_fill(S::text, today)::jsonb;

  -- wipe all business data (logins are kept)
  truncate table public.docs_payments, public.docs_documents, public.docs_catalog, public.docs_customers,
                 public.inv_counts, public.inv_movements, public.inv_products, public.inv_suppliers,
                 public.hr_punch_photos, public.hr_payslips, public.hr_salary_payments, public.hr_adjustments, public.hr_advances,
                 public.hr_kit, public.hr_tasks, public.hr_attendance, public.hr_pay, public.hr_employees,
                 public.push_log, public.push_subscriptions, public.portal_backups
  restart identity cascade;

  -- users
  for r in select * from jsonb_array_elements(S->'users') loop
    v_id := public.demo_login((r->>'username') || '@' || dom,
              case when r->>'username' = S->'settings'->>'demo_user' then S->'settings'->>'demo_password'
                   else encode(gen_random_bytes(18), 'base64') end);          -- sample users get a random password nobody knows
    delete from public.portal_users where username = r->>'username' and id <> v_id;   -- e.g. after the login domain changed
    insert into public.portal_users (id, username, full_name, is_admin, active, docs_role, inv_role, hr_role)
    values (v_id, r->>'username', r->>'full_name', (r->>'is_admin')::boolean, true, r->>'docs_role', r->>'inv_role', r->>'hr_role')
    on conflict (id) do update set username = excluded.username, full_name = excluded.full_name, is_admin = excluded.is_admin,
      active = true, docs_role = excluded.docs_role, inv_role = excluded.inv_role, hr_role = excluded.hr_role;
    v_user := v_user || jsonb_build_object(r->>'username', v_id);
  end loop;
  -- logins added by visitors (Users & Access is read-only in the demo, but just in case) are blocked
  update public.portal_users set active = false where not (username in (select x->>'username' from jsonb_array_elements(S->'users') x));
  v_mgr := (v_user->>'manager')::uuid;

  -- settings
  update public.hr_settings set company_name = S->'settings'->>'company', shift_hours = 9, off_day = 5, offday_ot_multiplier = 2,
         kit_template = coalesce(S->'kit_template', kit_template) where id = 1;
  off_day := 5;

  -- customers, price list, suppliers
  insert into public.docs_customers (code, name, name_ar, contact_person, phone, mobile, email, vat_no, buyer_id, address, city, payment_terms, created_by)
  select x->>'code', x->>'name', x->>'name_ar', x->>'contact_person', x->>'phone', x->>'mobile', x->>'email', x->>'vat_no', x->>'buyer_id',
         x->>'address', x->>'city', x->>'payment_terms', (v_user->>'yousuf')::uuid
    from jsonb_array_elements(S->'customers') x;
  insert into public.docs_catalog (category, subcategory, name, unit, rate)
  select x->>'category', x->>'subcategory', x->>'name', x->>'unit', (x->>'rate')::numeric from jsonb_array_elements(S->'catalog') x;
  insert into public.inv_suppliers (name, contact_person, phone, email)
  select x->>'name', x->>'contact_person', x->>'phone', x->>'email' from jsonb_array_elements(S->'suppliers') with ordinality t(x, i) order by i;

  -- products and stock movements (dated over the last 60 days)
  alter table public.inv_movements disable trigger user;
  insert into public.inv_products (sku, name, category, grade, thickness_mm, width_mm, length_mm, size, unit, weight_kg, min_stock, location, supplier_id)
  select x->>'sku', x->>'name', x->>'category', x->>'grade', (x->>'thickness_mm')::numeric, (x->>'width_mm')::numeric, (x->>'length_mm')::numeric,
         x->>'size', x->>'unit', (x->>'weight_kg')::numeric, (x->>'min_stock')::numeric, x->>'location', (x->>'supplier')::int + 1
    from jsonb_array_elements(S->'products') x;
  insert into public.inv_movements (product_id, type, qty, balance_after, reference, note, user_id, created_at)
  select p.id, m->>'type', (m->>'qty')::numeric,
         sum(case when m->>'type' = 'OUT' then -(m->>'qty')::numeric else (m->>'qty')::numeric end)
           over (partition by p.id order by (m->>'day')::int, i),
         m->>'reference', m->>'note', (v_user->>'ali.store')::uuid,
         ((today + (m->>'day')::int) + time '08:00' + make_interval(mins => ((i % 9) * 47)::int)) at time zone 'Asia/Riyadh'
    from jsonb_array_elements(S->'movements') with ordinality t(m, i)
    join public.inv_products p on p.sku = m->>'sku';
  update public.inv_products p set qty = (x->>'qty')::numeric from jsonb_array_elements(S->'products') x where p.sku = x->>'sku';
  alter table public.inv_movements enable trigger user;

  -- employees (kiosk PIN for everyone: 1234)
  insert into public.hr_employees (emp_code, name, designation, phone, active, pin_hash)
  select x->>'emp_code', x->>'name', x->>'designation', x->>'phone', coalesce((x->>'active')::boolean, true), crypt('1234', gen_salt('bf', 6))
    from jsonb_array_elements(S->'employees') x;
  insert into public.hr_pay (employee_id, basic_pay, ot_rate)
  select e.id, (x->>'basic_pay')::numeric, (x->>'ot_rate')::numeric
    from jsonb_array_elements(S->'employees') x join public.hr_employees e on e.emp_code = x->>'emp_code';

  -- attendance; on the weekly off day only some people come in (paid at the off-day overtime rate)
  for r in select * from jsonb_array_elements(S->'attendance') loop
    d := (r->>'date')::date;
    select id into v_emp from public.hr_employees where emp_code = r->>'emp';
    if extract(dow from d) = off_day then
      continue when abs(hashtext(r->>'emp' || d::text)) % 5 <> 0 or r->>'status' <> 'present' or d = today;
      insert into public.hr_attendance (employee_id, work_date, status, check_in, check_out, source, note)
      values (v_emp, d, 'present', (d + time '08:00') at time zone 'Asia/Riyadh', (d + time '13:30') at time zone 'Asia/Riyadh', 'admin', 'Friday overtime');
    else
      insert into public.hr_attendance (employee_id, work_date, status, check_in, check_out, source, note)
      values (v_emp, d, r->>'status',
              case when r ? 'cin' then (d + make_interval(mins => (r->>'cin')::int)) at time zone 'Asia/Riyadh' end,
              case when r->>'cout' is not null then (d + make_interval(mins => (r->>'cout')::int)) at time zone 'Asia/Riyadh' end,
              coalesce(r->>'source', 'admin'), r->>'note');
    end if;
  end loop;

  -- tasks, working kit, deductions / bonuses, advances
  alter table public.hr_tasks disable trigger user;
  insert into public.hr_tasks (employee_id, title, priority, status, assigned_on, due_date, completed_at, remarks, paid, amount, created_at, updated_at)
  select e.id, x->>'title', x->>'priority', x->>'status', (x->>'assigned_on')::date, (x->>'due_date')::date,
         case when x->>'status' = 'done' then ((x->>'due_date')::date + time '15:00') at time zone 'Asia/Riyadh' end,
         x->>'remarks', (x->>'paid')::boolean, (x->>'amount')::numeric, now(), now()
    from jsonb_array_elements(S->'tasks') x join public.hr_employees e on e.emp_code = x->>'emp';
  alter table public.hr_tasks enable trigger user;
  insert into public.hr_kit (employee_id, item, size, qty, issued_on, created_by)
  select e.id, x->>'item', x->>'size', (x->>'qty')::numeric, (x->>'issued_on')::date, (v_user->>'faraz')::uuid
    from jsonb_array_elements(S->'kit') x join public.hr_employees e on e.emp_code = x->>'emp';
  insert into public.hr_adjustments (employee_id, adj_date, kind, amount, reason, created_by)
  select e.id, (x->>'date')::date, x->>'kind', (x->>'amount')::numeric, x->>'reason', v_mgr
    from jsonb_array_elements(S->'adjustments') x join public.hr_employees e on e.emp_code = x->>'emp';
  insert into public.hr_advances (employee_id, given_on, amount, installment, note, created_by)
  select e.id, (x->>'date')::date, (x->>'amount')::numeric, (x->>'installment')::numeric, x->>'note', v_mgr
    from jsonb_array_elements(S->'advances') x join public.hr_employees e on e.emp_code = x->>'emp';
  -- last month's salaries were paid
  insert into public.hr_salary_payments (employee_id, month, paid_on, amount, method, reference, created_by)
  select e.id, to_char(date_trunc('month', today) - interval '1 month', 'YYYY-MM'), (date_trunc('month', today) + interval '1 day')::date,
         p.basic_pay, case when p.basic_pay >= 2500 then 'Bank transfer' else 'Cash' end, null, v_mgr
    from public.hr_employees e join public.hr_pay p on p.employee_id = e.id where e.active;

  -- documents (dated in the past, some approved by the manager)
  alter table public.docs_documents disable trigger user;
  alter table public.docs_payments  disable trigger user;
  for r in select * from jsonb_array_elements(S->'docs') loop
    if r ? 'link_invoice' then continue; end if;                 -- receipts that belong to a payment are made below
    d := today + coalesce((r->>'day')::int, 0);
    insert into public.docs_documents (doc_type, doc_no, doc_date, party_name, data, files, status, created_by, created_at,
                                       approved_by, approved_at, updated_by, updated_at)
    values (r->>'doc_type', r->>'doc_no', d, r->>'party_name', r->'data', coalesce(r->'files', '{}'), r->>'status',
            (v_user->>(r->>'by'))::uuid, (d + time '09:20') at time zone 'Asia/Riyadh',
            case when r->>'status' = 'approved' then v_mgr end,
            case when r->>'status' = 'approved' then ((d + time '14:10') at time zone 'Asia/Riyadh') end, null, null)
    returning id into v_doc;
    n_docs := n_docs + 1;
  end loop;
  -- invoice payments
  for v_inv in select * from jsonb_array_elements(S->'invoices') loop
    select id into v_doc from public.docs_documents where doc_type = 'invoice' and doc_no = v_inv->>'doc_no';
    insert into public.docs_payments (document_id, paid_on, amount, method, reference, created_by, created_at)
    select v_doc, today + (p->>'day')::int, (p->>'amount')::numeric, p->>'method', p->>'reference', (v_user->>'yousuf')::uuid,
           ((today + (p->>'day')::int) + time '11:00') at time zone 'Asia/Riyadh'
      from jsonb_array_elements(v_inv->'payments') p;
  end loop;
  -- cash receipts for those payments
  for r in select * from jsonb_array_elements(S->'docs') where value ? 'link_invoice' loop
    v_pay := null;
    select p.id, p.paid_on into v_pay, d
      from public.docs_documents d2 join public.docs_payments p on p.document_id = d2.id
     where d2.doc_type = 'invoice' and d2.doc_no = r->>'link_invoice' order by p.paid_on limit 1;
    continue when v_pay is null;
    insert into public.docs_documents (doc_type, doc_no, doc_date, party_name, data, status, created_by, created_at, approved_by, approved_at)
    select 'receipt', r->>'doc_no', d, r->>'party_name',
           (r->'data') || jsonb_build_object('amount', p.amount, 'due_total', i.data->'grand_total', 'paid_before', 0,
                                             'invoice_id', i.id, 'invoice_no', i.doc_no, 'payment_id', p.id, 'reference', p.reference),
           'approved', (v_user->>'yousuf')::uuid, (d + time '11:30') at time zone 'Asia/Riyadh', v_mgr, (d + time '15:00') at time zone 'Asia/Riyadh'
      from public.docs_payments p join public.docs_documents i on i.id = p.document_id where p.id = v_pay;
    n_docs := n_docs + 1;
  end loop;
  alter table public.docs_payments  enable trigger user;
  alter table public.docs_documents enable trigger user;

  update public.demo_seed set last_reset = now() where id = 1;
  return format('Demo data loaded: %s documents, %s employees, %s products, %s attendance days',
                n_docs, (select count(*) from public.hr_employees), (select count(*) from public.inv_products),
                (select count(*) from public.hr_attendance));
end $$;
revoke all on function public.demo_reset() from public, anon, authenticated;

-- "Reset demo data" button for the demo login: at most once every 10 minutes
create or replace function public.demo_reset_now()
returns text language plpgsql security definer set search_path = public as $$
declare s jsonb := (select data->'settings' from public.demo_seed where id = 1); last timestamptz;
begin
  if not exists (select 1 from public.portal_users where id = auth.uid() and username = s->>'demo_user') then
    raise exception 'Only the demo login can reset the demo.';
  end if;
  select last_manual_reset into last from public.demo_seed where id = 1;
  if last > now() - interval '10 minutes' then
    raise exception 'The demo was reset a few minutes ago. Please try again later.';
  end if;
  update public.demo_seed set last_manual_reset = now() where id = 1;
  return public.demo_reset();
end $$;
revoke all on function public.demo_reset_now() from public, anon;
grant execute on function public.demo_reset_now() to authenticated;

-- 4. schedule (Riyadh = UTC+3: 03:00 Riyadh is 00:00 UTC) ---------------
do $$ begin
  begin create extension if not exists pg_cron with schema pg_catalog;
  exception when others then
    begin create extension if not exists pg_cron; exception when others then null; end;
  end;
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('demo-nightly-reset', '0 0 * * *', $c$select public.demo_reset()$c$);
    perform cron.schedule('demo-login-repair', '17 * * * *', $c$select public.demo_fix_login()$c$);
    -- the real portal's weekly backup and morning summary are not needed in the demo
    begin perform cron.unschedule('portal-weekly-backup');   exception when others then null; end;
    begin perform cron.unschedule('portal-morning-summary'); exception when others then null; end;
    raise notice 'Nightly reset scheduled.';
  else
    raise warning 'Nightly reset NOT scheduled: enable Integrations > Cron in Supabase, then run this file again.';
  end if;
end $$;

-- 5. load the data now --------------------------------------------------
select public.demo_reset();
